###[[headers]]
  #for = "/*"
 # [headers.values]
  #  Content-Security-Policy = "script-src 'self' https://www.paypal.com https://www.paypalobjects.com; object-src 'none'"


  [[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' https://www.paypal.com https://www.paypalobjects.com https://eomail5.com https://cdnjs.cloudflare.com; object-src 'none'"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
