services:
  - type: web
    name: offszn
    staticPublishPath: . 
    
    rewrites:
      # Regla 1: Si la URL empieza con /@ (ej: /@willieinspired)
      - source: "/@:nickname"
        destination: "/usuarios.html"
        
      # Regla 2 (para el Owner): Si la URL es /producto/nombre-del-beat
      - source: "/producto/:slug"
        destination: "/pages/articulo.html" # (Lo haremos despu√©s)
        
      # Regla 3 (Fallback): Si nada coincide, sirve el index.
      - source: "/*"
        destination: "/index.html"